### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by iofjuupasli** [serjG901/todoProjectColobarate#3]
https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L235

No need to assign to argument

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L240

To make code less nested, use
```
if (title === "") {
  return;
}
...
```

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L242-L244

Use `const` in all that cases.

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L248-L251

What is purpose of that property? Isn't it possible to use `state.history.length`?

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L254-L261

Array spread is more modern way to concat

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L271

Avoid cloning

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L276-L295

Such parts of code can be extracted to pure functions

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L301

Invert condition

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L302-L320

Don't use let and move to pure function

https://github.com/serjG901/todoProjectColobarate/blob/da16fb0c5f3e3adb1520aed8d1c602825baeb8af/todoTask/action.js#L328-L354

All the same

**Comment by serjG901** [comment]
Fix this issue
